jenkins:
  nodes:
    - permanent:
        labelString: "Controller_Agent2"
        mode: NORMAL
        name: "controller_node"
        numExecutors: 2
        remoteFS: "/home/cddeploy/jenkins_2/"
        launcher:
          SSHLauncher:
            host: "192.168.0.130"
            port: 22
            credentialsId: agent
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:cddeploy"
        - "GROUP:Overall/Read:authenticated"

  remotingSecurity:
    enabled: true
jobs:
  - file: /var/jenkins_home/job_dsl/job.groovy
    
security:
  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy

unclassified:
  location:
    url: http://192.168.0.130:8080/
  SonarGlobalConfiguration:
    installations:
      - name: Sonarqube
        serverAuthenticationToken: "sqa_75a473269119e26cd79c57c9feda56893613c7a9"
        serverUrl: http://192.168.0.132:9000/
        triggers:
          skipScmCause: false
          skipUpstreamCause: false

tool:
  git:
    installations:
      - home: git
        name: default
  jdk:
    installations:
      - name: jdk20.0.1
        home: "/usr/java/jdk-20.0.1/"
credentials: # (5)
  system:
    domainCredentials:
      - domain :
          name: "github.com"
          description: "GitHub"
        credentials:
          - usernamePassword:
              scope: SYSTEM
              id: github-id
              username: sushant1305
              password: Sushant16#
          - usernamePassword:
              scope: GLOBAL
              id: "agent"
              username: "cddeploy"
              password: "admin123"
              description: "For connecting to agents"
